Updated aliases,computer,files_and_folders,fuzzy,pictures,programming,programs,shortcuts,surfing,troubleshoot,and wiki while working on vacation in Costa. Also created cheatsheets and education

diff --git a/computer b/computer
--- a/computer
+++ b/computer
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-
-
 function AndroidTest
 {
   case $OSTYPE in
@@ -17,9 +15,10 @@ esac
 function screensaver
 {
 
+ (command -v xscreensaver >/dev/null 2>&1 || { echo >&2 "Xscreensaver required but not installed. Aborting."; exit 1; })
+
 if ps -eo command | pgrep -x 'xscreensaver'; then
     echo "xscreensaver is running"
-
   xscreensaver-command -activate & 
 else
     echo "xscreensaver is not running"
@@ -31,31 +30,32 @@ function ComputerBios
 {
   sudo dmidecode -t bios -q;
 }
+function cmd
+{  
+  adrian ;
+  "/mnt/c/Windows/System32/cmd.exe";
+}
 
 function TerminalGet
 {
-#todo test for if neofetch installed
-cyan="\033[1;34m" 
 result=$(neofetch | grep Term| grep -iv font ) ;
 echo "$result"
 
+if [ "$result" -eq "" ]; then
+(command -v neofetch >/dev/null 2>&1 || { echo >&2 "Neofetch required but not installed. Aborting."; exit 1; })
+fi;
 }
 
-function ComputerBios
+function ComputerTerminal
 {
-  sudo dmidecode -t bios -q;
-}
-
-function TerminalGet
-{
-#todo test for if neofetch installed
-cyan="\033[1;34m" 
-result=$(neofetch | grep Term| grep -iv font | awk  -F\: '{print $2 }')
-printf "${cyan}Terminal: $result\n"
+  echo "$TERM";
 }
 
 function ComputerEnvironment
-{ npx envinfo ; }
+{ 
+ (command -v npx >/dev/null 2>&1 || { echo >&2 "Npx required but not installed. Aborting."; exit 1; })
+npx envinfo ; 
+}
 
 function ComputerWindowmgr
 {
@@ -64,8 +64,9 @@ function ComputerWindowmgr
 
 function ComputerGet
 {
-#todo test for if neofetch installed
-neofetch; }
+ (command -v neofetch >/dev/null 2>&1 || { echo >&2 "Neofetch required but not installed. Aborting."; exit 1; })
+neofetch; 
+}
 # cat /etc/os-release;
 # neofetch; consider switching to freshfetch. Also screenfetch is installed.
 # ~/.config/neofetch/config.conf
@@ -122,7 +123,6 @@ function ComputerHd
   #df -a -P -h -T | ( read -r head; printf '%s\n' "$head"; grep -Eiv '(-|loop|tmpfs)')
   lsblk -fl -o NAME,FSTYPE,SIZE,FSAVAIL,FSUSE%,MOUNTPOINT,LABEL | ( read -r head; printf '%s\n' "$head";grep -Eiv '(-|loop|tmpfs)') |
   awk -F '[ ]' '($4!="") {print}'
-
 }
 
 function ComputerUsb
@@ -130,9 +130,7 @@ function ComputerUsb
  # lsblk --help
  #df -h | ( read -r head; printf '%s\n' "$head"; grep --color=always -i multiboot);
  lsblk -fl -o NAME,FSTYPE,SIZE,FSAVAIL,FSUSE%,MOUNTPOINT,LABEL | ( read -r head; printf '%s\n' "$head"; grep --color=always -i multiboot) ;
-
 }
-
 
 function ComputerProgramsRunning
 {
@@ -141,14 +139,13 @@ function ComputerProgramsRunning
 
 function ComputerProgramKill
 {
-
    kill -9 $(pidof "$1")  ;
 }
+
 function ComputerProgramsInstalled
 {
   dpkg -l | awk -F ' ' '{$1=$3=$4=""; print $0}'| sed 's/ //' | awk 'sub(" ", "\t")' | column -t -s "$(printf '\t')" | fzf;
 }
-
 
 function PythonUpgradePip
 {
