added functions

diff --git a/programming b/programming
--- a/programming
+++ b/programming
@@ -1,15 +1,18 @@
 #!/bin/bash
 
+function copydir {
+  pwd | tr -d "\r\n" | pbcopy
+}
 
 function makeproject
 {
 
-  if [ ! "$#" -gt 0 ]; then read -p "Enter a project name: " project; fi ;
+  if [ ! "$#" -gt 0 ]; then read -r -p "Enter a project name: " project; fi ;
   if [ ! "$#" -eq 0 ]; then project=$1; fi
 
-mkdir ${project};
+mkdir  "${project}";
 
-cd ${project};
+cd "${project}" || exit ;
 touch index.html
 mkdir styles
 touch styles/main.css
@@ -21,4 +24,36 @@ function gpt
 {
 # https://github.com/jucasoliveira/terminalGPT/blob/main/README.md
 npx terminalgpt chat;
+}
+
+function getdiff 
+{
+  diff <($1) <($2);
+}
+
+function getdup
+{
+  find . | uniq -i -d
+}
+function jsonArrayToTable(){
+     jq -r '(.[0]|keys_unsorted|(.,map(length*"-"))),.[]|map(.)|@tsv'|column -ts $'\t'
+}
+
+function gethistory
+{
+# Returns last one hundred *unique* commands
+  history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' |
+    sort -rn | head -n 100
+}
+
+function topten 
+{
+        re='^[0-9]+$' 
+        if ! [[ $1 =~ $re ]] ; then 
+        echo "error: $1 not a number" >&2
+
+         else
+
+  history | awk '{cmd[$2]++} END {for(elem in cmd) {print cmd[elem], elem}}' | sort -n -r | head -n "$1";
+        fi
 }
